### ISSUE TITLE
Rasperry Pi loose contact with the Wixel

### ISSUE THREAD

**Issue by christerjensen** [jamorham/python-usb-wixel-xdrip#1]
I have a Raspberry Pi 2 with 4 USB-ports. After a few hours/days the python sctipt loose contact with the Wixel (the Wixel collects signals, and the python script acknowledge requests from the phone). The scrips does not get any values from the Wixel, so I guess it has lost contact with the Wixel. 

In your code you mention that the Wixel reboots and comes back as a new device. Have you written the code for the old Raspberry Pi with 2 USB-ports? Should I change the code to include all 4 USB-ports?
# sometimes the wixel reboots and comes back as a different

```
        # device - this code seemed to catch that happening
        # more complex code might be needed if the pi has other
        # ACM type devices.

        if (os.path.exists("/dev/ttyACM0")):
            ser = serial.Serial('/dev/ttyACM0', 9600)
        if (os.path.exists("/dev/ttyACM1")):
            ser = serial.Serial('/dev/ttyACM1', 9600)
```

**Comment by jamorham** [comment]
With the different ACM0/ACM1 devices, it isn't related to the physical USB port. As far as I understand it there is a timeout on the ACM device - so if the wixel reboots itself then linux will see a new device and find ACM0 is locked/already allocated so it will allocate ACM1 that time.

At some time later if the wixel reboots again this time it will find ACM0 isn't locked and so will use that device name. I am pretty sure that it will be either 0/1 assuming you have no other ACM type devices connected via usb.

With the reliability problem you report are you sure it is the script not receiving data from the wixel? 

If you can reproduce the problem I would be looking for things like:

Enable the lights option in the wixel code so you can see if its still flashing yellow or not. Wait for this lock-up to occur and then wait for the next sensor packet. If you see it flashing yellow then stop flashing you know it has received a packet and then look to see if the script is receiving anything at that point. 

If it doesn't receive anything over the serial we know that is where the problem is. I have 6 days uptime on my raspberry pi 2 and I haven't had to restart the script due to an issue with the serial/wixel before since I put in the code you quote above.

Please let me know what you find. Also check dmesg output and look for anything related to a usb error to see if that offers any clues.

**Comment by christerjensen** [comment]
During the first week, I've had to restart the Pi 3 times. I've made the Pi reboot every 24 hours now and restart the script as a background process. I will have to stop this and run it from the terminal so I can give more input.

The python script is running, xDrip is connecting and the last sniffed sensor info is repeated every time the xDrip connects in the terminal window (I see the sensor raw/filtered value is the same, but the time is different, this happens over and over again - there is no single line with the sensor values as is normal when the phone is not connected to the wifi network)

The wixel collects data as normal, it blinks every 5 minutes and stops. If I reboot the Raspberry Pi it collects the last data from the Wixel as normal and starts polling again.

It is only the time that changes in the 5 lines that pop up in the terminal everytime the phone polls the Raspberry PI IP.

**Comment by jamorham** [comment]
Okay I think I may know what could cause this issue. I will try to add a watchdog feature to correct it when it occurs and we can try that.

**Comment by christerjensen** [comment]
I've had no issues since I made the Rasberry PI reboot every 24 hour with a cron job. 

I bought another Raspberry PI and will set that up with your new updated script without a reboot and see how it goes.

**Comment by jamorham** [comment]
Okay great, please let me know, there is also now the remoteHosts[] feature so you can make one pi load the data from another one and then avoid needing to add multiple host entries within the xdrip app.

**Comment by christerjensen** [comment]
Installed the lastest version on a new Raspberry PI. 

It has been rock solid for 8 days now - I even disconnected the Wixel without restarting the script and it connected automatically. Very good!

**Comment by jamorham** [comment]
Okay, so do I understand correctly that this latest version of the script fixes the problem or did you change anything else? Are you still restarting with a cron job?

**Comment by christerjensen** [comment]
The script fixes the problem, no cron job on my new Raspberry Pi. If I remove the Wixel for a few minutes it automatically connects when I plug it in again. Problem solved! Thanks.

**Comment by jamorham** [comment]
Great news! Thank you.
